### ISSUE TITLE
Submissions: 405 Client Error: Method Not Allowed

### ISSUE THREAD

**Issue by s1mahoeg** [icfpcontest2020/dockerfiles#55]
What I've done:
- [x] created a private Git repository
- [x] copied the deploy key and added it to the repository
- [x] created a branch called `submission`
- [x] downloaded a starter kit
- [x] committed and pushed the starter kit
- [x] waited for more than 10 minutes

Here's the problem:

I got the following error: 405 Client Error: Method Not Allowed.

It's the first time I got the error. So far I (almost) only changed stuff in my developer-folder. So the failed-test was basically the python starter-kit. I guess there is a problem with the server? Here is the corresponding test log:

```bash
ServerUrl: http://server:12345; PlayerKey: 4545917190182324706
<Response [405]>
Traceback (most recent call last):
  File "app/main.py", line 14, in <module>
    main()
  File "app/main.py", line 8, in main
    utils.start(server_url=sys.argv[1],
  File "/solution/app/icfp_lib/utils.py", line 6, in start
    res.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://server:12345/?playerKey=4545917190182324706
```

I wasn't sure if I should create an issue for this. Are you providing information about the server status somewhere? So that we do not create unnecessary issues if you already know about problems / planned reconfiguring of the server etc?

**Comment by s1mahoeg** [comment]
Ah, the updated starter-kit fixed the problem.
