### ISSUE TITLE
Submissions: python alien/send request fails

### ISSUE THREAD

**Issue by s1mahoeg** [icfpcontest2020/dockerfiles#91]
What I've done:
- [*] created a private Git repository
- [*] copied the deploy key and added it to the repository
- [*] created a branch called `submission`
- [*] downloaded a starter kit
- [*] committed and pushed the starter kit
- [*] waited for more than 10 minutes

Here's the problem:

I'm using python. The starter-kit works. But when I replace the post command with:

```python
import requests
res = requests.post("https://icfpc2020-api.testkontur.ru/aliens/send?apiKey=<my-api-key>", data="string")
```

then the testing stages fails with:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7feabcc7e490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='icfpc2020-api.testkontur.ru', port=443): Max retries exceeded with url: /aliens/send?apiKey=<my-api-key> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feabcc7e490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/main.py", line 14, in <module>
    main()
  File "app/main.py", line 8, in main
    utils.start(server_url=sys.argv[1],
  File "/solution/app/icfp_lib/utils.py", line 10, in start
    res = requests.post(url, data=data)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='icfpc2020-api.testkontur.ru', port=443): Max retries exceeded with url: /aliens/send?apiKey=<my-api-key>(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feabcc7e490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

Am I doing something wrong?

**Comment by s1mahoeg** [comment]
I used the wrong url and api-key. One has to use the ones provided by argv
